### ISSUE TITLE
Switches Dataset Field Additions

### ISSUE THREAD

**Issue by D1R2** [kartsims/mechdb#46]
Hey @kartsims, @ReeceJones , @kirontoo 
Someone from the switch discord shared this great switch database with me: https://docs.google.com/spreadsheets/d/1SI8LOKkXbYj8WP9i6IoawLgcgr3jKySPRI0uh3fI6dM/edit?usp=sharing

There are a few things here that need to be added / changed to the switches dataset before I input it all: 
1. Change 'Name' to 'Variant'
2. Add 'Spring Weight'
3. Add 'Actuation Distance
4. Add 'Silenced' Checkbox
5. Change 'Retail' to 'In Production
6. Add 'Box' to stem type
7. Add 'Clear Shell/RGB Option' Checkbox

I think that should cover it and then I can input this into the database pretty quickly.

**Comment by kartsims** [comment]
> Change 'Name' to 'Variant'

I think the name should use the datasheet's "Brand + Variant" columns, because the manufacturer is Gateron in some cases. Not sure if it is important to rename "name" to "variant" as "name" is referring to the name to which we usually refer to the switch.
Also some lines use the same "brand + variant" (see lines 8 and 9, or even lines 204-207). In our website we have to make sure all names are unique or this would cause some weird behavior.

> Add 'Spring Weight'
> Add 'Actuation Distance
> Add 'Silenced' Checkbox
> Add 'Clear Shell/RGB Option' Checkbox

Noted

> Change 'Retail' to 'In Production

The way I see it is :
- Retail = YES → the switch is "in production" (I can change "retail" to "in production" but this will affect the other datasets. I don't mind it, it does make sense imo)
- Retail = NO → the switch might be either a GB, or has ended production. Either way, unless notes are available, we should leave the "Availability" field blank

> Add 'Box' to stem type

It seems to me that "Box" means MX boxed (since all switches appear to be MX). They look [like this](https://massdrop-s3.imgix.net/product-images/novelkeys-x-kailh-box-thick-clicks-switches/1Zf6gUh9SwCyk4m6gS75_361A7414.jpg?auto=format&fm=jpg&fit=crop&w=955&bg=f0f0f0&dpr=1). We could add a "boxed" checkbox but I am not sure if this is important to use it as a search field... If it is not, I'd rather leave it to the user to see by himself. We could ask the switches guys about that

**Comment by kartsims** [comment]
Could we also make sure that "Spring Weight" isn't the same as "Bottom out force" ? This issue is blocking the content population of the switches dataset, we should treat it as high priority

**Comment by kartsims** [comment]
Added today:
- Clear Shell/RGB Option
- Actuation Length
- Silenced

**Comment by Vloshko** [comment]
I clarified everything one needs to know about springs in the google doc datasheet for you guys.

**Comment by kartsims** [comment]
The following subjects are pending:
- add a "boxed"  checkbox, for boxed MX stem types. I don't think it really matters... question is: would anyone search for something that is boxed or not, or is it just a nice information to have on the page directly ?
- does "spring weight" match "bottom out force" ? we want to get things right when scraping [the google sheet](https://docs.google.com/spreadsheets/d/1SI8LOKkXbYj8WP9i6IoawLgcgr3jKySPRI0uh3fI6dM/edit?)
- do we need the "plating" option for switches ? if so I guess we should call it "spring plating" right?

**Comment by kirontoo** [comment]
@kartsims "spring weight" is usually measured by "bottom out force" since the actuation force is different depending on the switch. From the google sheet, I believe that it's bottom out force

**Comment by kartsims** [comment]
dropped switches support
